name: CI/CD Pipeline

on:
  push:
    branches:
      - development


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' 

      - name: Build project
        run: dotnet restore; dotnet publish -o site;

      - name: Run Tests
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release -o ./output

      - name: create zip package
        run: cd site; zip ../site.zip *;

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'  # Deployment endast vid PR till main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Encryption API
          environment_name: EncryptionAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip
