name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' 

      - name: Build
        run: dotnet build

      - name: Run Tests
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release -o ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'  # Deployment endast vid PR till main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb init -p dotnet core -r eu-north-1 EncryptionAPI --region eu-north-1
          eb deploy
